# Generated by Django 5.2.15 on 2026-09-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitebrandingsettings',
            name='site_name_first',
        ),
        migrations.RemoveField(
            model_name='sitebrandingsettings',
            name='site_name_second',
        ),
        migrations.RemoveField(
            model_name='sitebrandingsettings',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='sitebrandingsettings',
            name='site_name',
            field=models.CharField(default='Site name', max_length=160, verbose_name='Nom du site'),
        ),
    ]
