# Generated by Django 5.2.15 on 2026-09-03 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sitebrandingsettings_site_name_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitebrandingsettings',
            name='logo_image',
        ),
        migrations.AddField(
            model_name='sitebrandingsettings',
            name='logo_svg',
            field=models.FileField(blank=True, help_text='Logo SVG affiché à gauche du titre.', upload_to='site-branding/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Logo SVG'),
        ),
    ]
