# Generated by Django 5.2.15 on 2026-09-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sitebrandingsettings_logo_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitebrandingsettings',
            options={'verbose_name': 'Identité du site', 'verbose_name_plural': 'Identité du site'},
        ),
    ]
